# Dockerfile.backend

# Use the official Node.js image for the backend
FROM node:18 AS backend

# Set the working directory for the backend
WORKDIR /usr/src/app/backend

# Copy package.json and package-lock.json
COPY backend/package*.json ./

# Install backend dependencies
RUN npm install

# Copy the rest of the backend application code
COPY backend .

# Expose the backend port
EXPOSE 3004

# Start the backend application
CMD ["npm", "run", "dev"]
